
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
<center><h2>Conexión con Tera Chat</h2></center>
<div class="row"></div>
    <div class="col-12">
        <div class="input-group mb-3">
            <span class="input-group-text">Tera Token</span>
            <input type="text" class="form-control" placeholder="tera_token" aria-label="tera_tolen" aria-describedby="button-addon2", id="tera_token" value="<?= get_option("tera_notif_token", "") ?>">
            <span class="input-group-text" id="detector"><i class="bi bi-app"></i></span>
            <button class="btn btn-outline-primary" type="button" id="button-addon2" onclick="active()">Verificar</button>
        </div>
    </div>
</div>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>

<script>
    let $ = jQuery;
    let ajax_url = '<?php echo admin_url("admin-ajax.php"); ?>';

    async function active(){
        setStatusDetector("wait", "detector");
        const request = await $.when(
            $.post(ajax_url, {
                action: "save_tera_token",
                tera_token: $("#tera_token").val()
            })
        ).done(resp => {
            if(resp == "ok"){
                setStatusDetector("done", "detector");

            }else{
                setStatusDetector("error", "detector");
            }
        });
    }

    function setStatusDetector(stat, id){
        let str = "";
        switch(stat){
            case "wait": str = '<i class="bi bi-hourglass"></i>'; break;
            case "done": str = '<i class="bi bi-check2" style="color: green"></i>'; break;
            case "error": str = '<i class="bi bi-x" style="color: darkred"></i>'; break;
        }
        $("#"+id).html(str);
    }
</script>